# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {}

# override variables
variables:
  trmnl: {}
  version: 2
  render_time: "7:35 AM"
  list_name: "Reminders"
  reminders:
    - idx: 1
      date: ""
      title: TRMNL Reminders Recipe
      num_tasks: 0
      description: Stay on top of your Apple Reminders
    - idx: 2
      title: Now on version 2
      date: "7/23/25, 00:00"
      num_tasks: 0
      description: With better layouts and more details
    - idx: 3
      date: ""
      title: Below are example reminders
      num_tasks: 0
      description: for the recipe thumbnail
    - idx: 4
      date: "Today, 16:00"
      title: Grab items from the store
      num_tasks: 4
      description: ""
    - idx: 5
      date: "Tomorrow, 12:00"
      title: Walk the cat
      num_tasks: 0
      description: ""
    - idx: 6
      date: "6/21/25, 18:30"
      title: Do a large task
      num_tasks: 8
      description: "This task has many details, including a long description that should get truncated"
    - idx: 7
      date: "6/21/25, 00:00"
      title: Wash the car
      num_tasks: 0
      description: ""
    - idx: 8
      date: "6/29/25, 00:00"
      title: Pay bills
      num_tasks: 0
      description: ""
    - idx: 9
      date: "7/14/25, 00:00"
      title: Prepare for conference
      num_tasks: 0
      description: Review slide deck and key points
